name: Atualizador de Lista IPTV

on:
  schedule:
    # Roda automaticamente a cada 3 horas
    - cron: '0 */3 * * *'
  workflow_dispatch: # Permite que você clique em um botão para atualizar manualmente quando quiser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências de rede e o yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Executar o script conversor
      run: python atualizar_lista.py

    - name: Salvar e atualizar o arquivo m3u no GitHub
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add lista.m3u
        git commit -m "Lista atualizada automaticamente" || exit 0
        git push
